export * from './resume';
export * from './fast';
export * from './functional';
export * from './responsive';
export * from './easyToUse';
export * from './birthday';
export * from './employee';
export * from './school';
export * from './student';